# Generated by Django 4.0.6 on 2022-07-22 16:16

from django.db import migrations, models
import projects.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=126)),
                ('type', models.CharField(max_length=126, null=True)),
                ('slug', models.CharField(max_length=126, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=projects.models.upload_img_project)),
                ('link_website', models.CharField(max_length=126)),
                ('link_repository', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
