# Generated by Django 4.0.6 on 2022-07-14 22:56

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_img_project),
        ),
    ]
