# Generated by Django 4.0.6 on 2022-07-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.CharField(max_length=126, null=True),
        ),
    ]
